### ISSUE TITLE
Crash when placing beacon without a base

### ISSUE THREAD

**Issue by ChloeDawn** [ChloeDawn/BeaconOverhaul#3]
**Describe the bug**
The game crashes when placing a beacon in a location that would not be considered valid

**Reproduction steps**
1. Place beacon in the world with no base blocks

**Expected behavior**
The beacon should just not function, remaining dormant

**Environment (please complete the following information):**
 - Minecraft version: 20w51a
 - Loader version 0.11.1
 - Mod version 1.0.0

**Additional context**
```
java.lang.IllegalArgumentException
	at dev.sapphic.beacons.BeaconTier.of(BeaconTier.java:29)
	at dev.sapphic.beacons.TieredBeacon.updateBaseAndTier(TieredBeacon.java:54)
	at net.minecraft.class_2580.redirect$zzo000$updateBaseAndTier(class_2580.java:562)
	at net.minecraft.class_2580.method_16896(class_2580.java:177)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:884)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:939)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:423)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:870)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:810)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ChloeDawn** [comment]
https://github.com/ChloeDawn/BeaconOverhaul/commit/3e4e951e2a09407fe69b634aa3339166a6cc6892
