### ISSUE TITLE
Incompatible with optifabric/optifine

### ISSUE THREAD

**Issue by Murilo-de-Carvalho** [ChloeDawn/BeaconOverhaul#46]
**Describe the bug**
The game crashes when I try to open it with optifabric and optifine active in the modpack

**Screenshots**
![image](https://github.com/ChloeDawn/BeaconOverhaul/assets/56364055/cf2c2413-71be-4ede-8e2b-6d54f360d666)
It's in portuguese cus i'm brazilian

**Environment (please complete the following information):**
 - Minecraft version: 1.20.1
 - Loader version fabric-api-0.91.1+1.20.1
 - Mod version BeaconOverhaul-1.8.4+1.20

**Additional context**
Removing optifabric and optifine or disabling them will make the mod work

**Crash code**
Time: 2024-02-11 13:21:58
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_765 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_757.<init>(class_757.java:296)
	at net.minecraft.class_310.<init>(class_310.java:580)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method fullBrightNightVision(F)F in mixins/beaconoverhaul/mixins.client.json:LightTextureMixin from mod beaconoverhaul failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins/beaconoverhaul/refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more

If any additional info is needed I'll try to convey it

Sorry for possible grammar mistake, as I said, I'm brazillian

**Comment by ChloeDawn** [comment]
I do not plan to fix any compatibility issues with OptiFine, please refer to https://optifine.alternatives.lambdaurora.dev/
